### PR TITLE
Fixed sql injection vulnerability

### PR DESCRIPTION
**Pull request by Addisonbean**
I never actually ran these changed because I didn't want to setup the database and all, but you have a REALLY bad sql injection vulnerability that needed to be fixed. This should work, but if not it shouldn't be too hard to get it working. Also, you may want to add more validation to `validate_quiz_request`, idk.

### CODE REVIEW

**Comment by Addisonbean** [comment]
Also turn debug mode off on your server.

**Comment by mpreyes** [comment]
> I never actually ran these changed because I didn't want to setup the database and all, but you have a REALLY bad sql injection vulnerability that needed to be fixed. This should work, but if not it shouldn't be too hard to get it working. Also, you may want to add more validation to `validate_quiz_request`, idk.

Hey thanks for letting us know, we are working to patch some of these issues. 

> Also turn debug mode off on your server.

Both of these things you mentioned  were due to lack of time, we chose to leave debug mode on since we were having problems getting some of the static files to load (on debug mode, Django serves these files for you). I'm not sure I want to change some of these things since we are already in production, but I'll bring it to the team and see if we might be able to make some changes at like midnight or something.

Thanks for letting us know, Addison!

**Comment by mpreyes** [comment]
Also, would you like to join ACM next year? we are looking for members to fill our spots for leadership roles.

**Comment by ambrosiogabe** [comment]
Hey Addison, we added some SQL injection protection to the code that is actually on the server. Thank you for your code proposal and your suggestions. We decided to not go forward with the code proposals that you gave because we have some validation via Javascript in the browser, which 99% of the population do not know how to get around. For the other 1% however, we did add some validation in the backend that had the same concept as what you proposed, but checked for different more dangerous snippets of code.

**Comment by Addisonbean** [comment]
@ambrosiogabe Awesome great! So it's safe for me to go and try to drop table lustudent? Even if the 99% can't, it only takes one person who's read about basic sql injection to mess everything up.

**Comment by ambrosiogabe** [comment]
Go for it buddy. We're not idiots, we put this site up live knowing full well that debug was off, knowing full well that we ran the possibility of having a SQL injection attack, knowing full well that it was not in a complete state, but we figured the only people who had the knowledge of how to mess something like this up, the people in the CCT, would be very inconsiderate of even thinking of trying something like that since, you know, we're kind of raising money using this for the only club that the CCT has which all Computer Science students are a part of. In the off chance that someone outside the CCT had the knowledge of how to break our app, we figured that they wouldn't want to waste their time trying to ruin a dating service. On the off chance that they did want to waste their time trying to break our app, we figured that it would be pretty childish of a college student to disrupt a fundraising service for a club local to their college. But, thank you for letting us realize that in the future we should probably invest more time in protecting this app, because there are actually people in our school who are childish enough to try to break it simply because they can.

**Comment by Addisonbean** [comment]
I'm sorry, I shouldn't have said anything.

**Comment by ambrosiogabe** [comment]
You're good, you didn't hurt anything but my pride :). I was in charge of security of the app since I created that portion of the code, and I was very negligent. We are glad that you pointed it out because we were wondering if it was necessary or not, and honestly, we should have added it in it was like two lines of code. Like Madelyn said though we would appreciate the help if you would want to consider joining next year :)

**Comment by mpreyes** [comment]
No no, thank you for saying something. There were definitely some vulnerabilities and since you pointed them out we were able to fix some of them. 

We are all just feeling a bit testy over here since everything that could have gone wrong with this project, did. From not having a server that could support the correct version of python, to having to set up a bank account and having a million issues with setting up payments, to having to reformat our profile page, all of the testing time that we allotted went out the window and we were forced to test as it was going live in order to meet the deadline.

To add on top of that, we've had to man the payment booth by ourselves since no one wanted to sign up for shifts. Meaning that we've spent probably a good part of this month pretty much living and breathing bison match. 

No hard feelings, man!

**Pull request closed without merging**
